### ISSUE TITLE
Setting the CRAN mirror via ~/.Rprofile does not seem to work

### ISSUE THREAD

**Issue by Anirban166** [Anirban166/Autocomment-atime-results#33]
Tried `echo "options(repos = c(CRAN = 'https://cloud.r-project.org'))" >> ~/.Rprofile` at first, but it failed to detect the CRAN mirror.

Found out that the dotfile was located elsewhere:
```sh
print(normalizePath('~/.Rprofile'))
/github/home/.Rprofile
```
Corrected the path to it and printed out the contents after inserting to check:
```sh
echo "options(repos = c(CRAN = 'https://cloud.r-project.org'))" >> /github/home/.Rprofile
cat /github/home/.Rprofile
```
```sh
Sys.setenv("PKGCACHE_HTTP_VERSION" = "2")
options(
  repos = c(
    RSPM = 'https://packagemanager.posit.co/cran/__linux__/focal/latest',
    CRAN = 'https://cran.rstudio.com'
  ),
  Ncpus = 1,
  HTTPUserAgent = sprintf("R/%s R (%s) on GitHub Actions", getRversion(), paste(getRversion(), R.version$platform, R.version$arch, R.version$os))
)
options(repos = c(CRAN = 'https://cloud.r-project.org'))
```
Still fails:
```sh
Error in contrib.url(repos, type) : 
  trying to use CRAN without setting a mirror
Calls: install.packages -> startsWith -> contrib.url
Execution halted
Error: Process completed with exit code 1.
```

**Comment by Anirban166** [comment]
> it could be that R is being run with R --vanilla, is that it? (in that case .Rprofile is not read)

Just checked, it doesn't seem to be the case:
```sh
Rscript -e "cat('R running with --vanilla:', '--vanilla' %in% commandArgs(trailingOnly = FALSE), '\n')"
```
```
R running with --vanilla: FALSE 
```
The only flags in the argument list are `--no-echo` and `--no-restore`.

**Comment by Anirban166** [comment]
>   Then, unless '--no-init-file' was given, R searches for a user
     profile, a file of R code.  The path of this file can be specified
     by the 'R_PROFILE_USER' environment variable (and tilde expansion
     will be performed).  If this is unset, a file called '.Rprofile'
     is searched for in the current directory or in the user's home
     directory (in that order).  The user profile file is sourced into
     the workspace.

^This was helpful!
Since my .Rprofile wasn't being used when at `/github/home/`(unless I explicitly run that step with `env` having `HOME: /github/home`), I copied it to the current directory following that description of it being searched for in the current directory. 
I tested its functioning by setting an environment variable inside the copied `.Rprofile` and then tried to access it:
```sh
echo $R_PROFILE_USER
cp /github/home/.Rprofile .
echo "Sys.setenv(R_PROFILE_LOADED = 'TRUE')" >> .Rprofile
echo "options(repos = c(CRAN = 'https://cloud.r-project.org/'))" >> .Rprofile
Rscript -e 'Sys.getenv("R_PROFILE_LOADED")'
```
```
[1] "TRUE"
```
Looks like it is working now so I made the transition in my [workflow](https://github.com/Anirban166/data.table/blob/before-4491-got-merged/.github/workflows/autocomment.yml) to avoid the repetition of setting the CRAN mirror.

**Comment by tdhock** [comment]
great now can you please remove the git switch? (or document why it is not possible)

**Comment by Anirban166** [comment]
> great now can you please remove the git switch? (or document why it is not possible)

[Did so](https://github.com/Anirban166/data.table/commit/d70cbb5d5a3668e4529a3cfa2a449822f5bd3c9c) and as you can [see](https://github.com/Anirban166/data.table/pull/2#issuecomment-1996644103) all the branches (merge-base, base, master) aren't detected by `atime` without it: (like I mentioned to you before)

<img width="1019" alt="image" src="https://github.com/Anirban166/Autocomment-atime-results/assets/30123691/1f6c00d0-9bb3-4edc-a94b-b8257e4d9d4f">

As opposed to having them:

<img width="741" alt="image" src="https://github.com/Anirban166/Autocomment-atime-results/assets/30123691/a93f93b4-1514-4041-9ae3-1f7a886a61f9">

I wrote a condensed comment before I deleted it, that it's required for 'checks between branches' but I'll write a more detailed one.

You were asking before why the checkout step wasn't sufficient alone, and that's because `checkout` by default *does not* create local branch references for each branch in the repository. To elaborate, this means that the local environment might not have branch names available for use in commands that expect them, like some `git` operations that you are using under the hood with `atime`.

More specifically `git2r::revparse_single`, which is used to find a specific revision (such as a commit, branch, or tag). For this function to work correctly, especially in the context of analyzing pull requests like our case, the local repository needs to have references to the branches. This is where the `git switch` commands come into play - they are used to ensure these local branch references exist.

As you can see now with the first plot, the workflow did not switch to the branches explicitly and`git2r` was not able to properly retrieve the branch references it needed when I deleted that step.

**Comment by tdhock** [comment]
ok thanks for the explanation. that is helpful to see the figure showing what it looks like when it is omitted. 

however your explanation seems to contradict https://docs.github.com/en/actions/learn-github-actions/variables#default-environment-variables which says that `GITHUB_BASE_REF` is a default environment variable that is available at every step of the workflow, "The name of the base ref or target branch of the pull request..." which implies that the "base=" line on the plot should be available (even without git switch). But in your plot it only has has HEAD= (not base=). I don't understand why, do you?

can you please add a small comment with a simpler version of this explanation in the action yaml file with a link to this comment?

I do not see any explanation about why git switch is needed twice, can you please explain? (it seems to me like once should be sufficient?)

**Comment by Anirban166** [comment]
> however your explanation seems to contradict https://docs.github.com/en/actions/learn-github-actions/variables#default-environment-variables which says that GITHUB_BASE_REF is a default environment variable that is available at every step of the workflow, "The name of the base ref or target branch of the pull request..." which implies that the "base=" line on the plot should be available (even without git switch). But in your plot it only has has HEAD= (not base=). I don't understand why, do you?

You're right that `GITHUB_BASE_REF` (and also `GITHUB_HEAD_REF`) are available as environment variables in GHA workflows, and I too reckon that these variables should provide the names of *both* the base and head branches associated with the pull request, so nope, I do not understand either why the `base=` label does not pop up in that plot :(

But either way, having just these names available as environment variables does not automatically mean that local branch references are created in the git repository checked out by the GitHub Actions runner.

> can you please add a small comment with a simpler version of this explanation in the action yaml file with a link to this comment?

Sure, and I actually added [that](https://github.com/Anirban166/data.table/commit/efa81d581c0492ce21ba24e09809ba7da26abe07) before you commented - can you please check if this is good enough? (and yes I'll add the link once I hear back on this)

> I do not see any explanation about why git switch is needed twice, can you please explain? (it seems to me like once should be sufficient?)

It's not the same thing twice, it's for two different refs: (base and head)
```sh
git switch "${GITHUB_BASE_REF}"
git switch "${GITHUB_HEAD_REF}"
```
The first git switch is used to check out the *base* branch, and the second switch checks out the *head* branch. This is to ensure that both branches are checked out at least once during my workflow to create the local references needed for BASE and HEAD (in other words, switching to each once ensures these references are available locally since we require explicit references to both branches).

And if I were to not use `git switch` and instead `git checkout` (since we discussed the difference between them much earlier, or as to why not use `git checkout` instead), an equivalent but more verbose way to do that would be:
```sh
...

    steps:
    - name: Checkout
      uses: actions/checkout@v4
      with:
        fetch-depth: 0

    - name: Setup local branch for BASE_REF
      run: |
        # Using git fetch here since checkout does not automatically attempt to fetch the branch from the remote if it doesn’t exist locally: (unlike git switch) 
        git fetch origin ${GITHUB_BASE_REF}:${GITHUB_BASE_REF}
        git checkout ${GITHUB_BASE_REF}

    - name: Setup local branch for HEAD_REF
      run: |
        git fetch origin ${GITHUB_HEAD_REF}:${GITHUB_HEAD_REF}
        git checkout ${GITHUB_HEAD_REF}

...
```
(Again, note that `actions/checkout` only clones the repository and checks out the commit that triggered the workflow, so while it does set up a working copy of the project, it does not create local branch references for the base and head branches of the pull request by default)

**Comment by tdhock** [comment]
Thank you for the very clear explanation. Excellent work!

**Comment by Anirban166** [comment]
> Thank you for the very clear explanation. Excellent work!

Happy to hear!
