### ISSUE TITLE
Speed up builds with selective install?

### ISSUE THREAD

**Issue by MichaelChirico** [Anirban166/Autocomment-atime-results#35]
https://github.com/Anirban166/Autocomment-atime-results/blob/6474b648a297e0ff699658054c83acbfd6748bcc/action.yml#L47

```
Suggests:	directlabels, ggplot2, testthat, knitr, markdown, stringi, re2, binsegRcpp, wbs, fpop, changepoint, LOPART, cumstats, PeakSegDisk, callr, readr, dplyr, tidyr, nc, RColorBrewer
```

{atime} has a lot of Suggests dependencies, I doubt they are all needed for the GHA (though {ggplot2} obviously is) -- should we try a more selective approach instead? I imagine it could have a pretty big impact on the setup duration.

**Comment by Anirban166** [comment]
I agree on the topic of minimizing dependencies for faster setup time and that most of the ones you mentioned above are not required for my GHA (only `directlabels` and yes, `ggplot2`). 

In fact that's what I initially did, but @tdhock suggested to install `atime` using `dependencies = TRUE` instead, so I made the switch in 7fc823e from specifying essential packages to the current form:
https://github.com/Anirban166/Autocomment-atime-results/blob/6474b648a297e0ff699658054c83acbfd6748bcc/action.yml#L47

At that time, my understanding was that R packages listed under 'Suggests' would not be installed aside from the hard dependencies so I thought that was acceptable, but I do see this right now:

<img width="1131" alt="image" src="https://github.com/user-attachments/assets/7ee8770f-1c99-4649-965b-48af27dd23fd">

So I'm currently testing things with a new version of my action that just installs the required packages to see if there is any noticeable difference - will keep you guys posted :)

**Comment by MichaelChirico** [comment]
I count 94 packages required to install atime+its Suggests vs. 22 to minimall install atime and 56 to install atime+ggplot2

```
optional_direct = package_dependencies("atime", which=c("Imports", "Depends", "Suggests"))
required_for_optional = package_dependencies(c("atime", unlist(optional_direct)), recursive=TRUE) 
length(unique(c(unlist(optional_direct), unlist(required_for_optional))))
# [1] 94
sum(lengths(package_dependencies("atime", recursive=TRUE)))
# [1] 22
sum(lengths(package_dependencies(c("atime", "ggplot2"), recursive=TRUE)))
# [1] 56
```

**Comment by Anirban166** [comment]
Thanks! 
That is helpful and yes, there should be a clear difference in setup time from just specifying to use 'Imports' plus installing the two dependencies from 'Suggests' for plotting.

**Comment by Anirban166** [comment]
I'm observing an improvement of ~20 seconds from the change I made in 0346c41 (simply went with what I did before except needing to install `remotes`, which was required much earlier when a core functionality of `atime` was on GitHub and not on CRAN), which I published as [v1.2.1](https://github.com/Anirban166/Autocomment-atime-results/releases/tag/v1.2.1).

Current set of dependencies:

<img width="1110" alt="image" src="https://github.com/user-attachments/assets/449f48a7-07ba-423a-8d4e-799327f0c5c5">

Looks about right:
```r
tools::package_dependencies(c("atime", "directlabels", "ggplot2"), recursive = TRUE)
```
```
$atime
 [1] "data.table" "bench"      "lattice"    "git2r"      "utils"      "stats"      "grDevices" 
 [8] "glue"       "methods"    "pillar"     "profmem"    "rlang"      "tibble"     "graphics"  
[15] "grid"       "cli"        "fansi"      "lifecycle"  "utf8"       "vctrs"      "magrittr"  
[22] "pkgconfig" 

$directlabels
[1] "grid"     "quadprog"

$ggplot2
 [1] "cli"          "glue"         "grDevices"    "grid"         "gtable"       "isoband"     
 [7] "lifecycle"    "MASS"         "mgcv"         "rlang"        "scales"       "stats"       
[13] "tibble"       "vctrs"        "withr"        "utils"        "methods"      "nlme"        
[19] "graphics"     "Matrix"       "splines"      "farver"       "labeling"     "munsell"     
[25] "R6"           "RColorBrewer" "viridisLite"  "fansi"        "magrittr"     "pillar"      
[31] "pkgconfig"    "colorspace"   "lattice"      "utf8"  
```

**Comment by Anirban166** [comment]
I'm observing an improvement of ~20 seconds from the change I made in 0346c41 (simply went with what I did before except needing to install `remotes` - required much earlier when a core functionality of `atime` was on GitHub and not on CRAN), which I published as [v1.2.1](https://github.com/Anirban166/Autocomment-atime-results/releases/tag/v1.2.1).

Current set of dependencies:

<img width="1110" alt="image" src="https://github.com/user-attachments/assets/449f48a7-07ba-423a-8d4e-799327f0c5c5">

Looks about right:
```r
tools::package_dependencies(c("atime", "directlabels", "ggplot2"), recursive = TRUE)
```
```
$atime
 [1] "data.table" "bench"      "lattice"    "git2r"      "utils"      "stats"      "grDevices" 
 [8] "glue"       "methods"    "pillar"     "profmem"    "rlang"      "tibble"     "graphics"  
[15] "grid"       "cli"        "fansi"      "lifecycle"  "utf8"       "vctrs"      "magrittr"  
[22] "pkgconfig" 

$directlabels
[1] "grid"     "quadprog"

$ggplot2
 [1] "cli"          "glue"         "grDevices"    "grid"         "gtable"       "isoband"     
 [7] "lifecycle"    "MASS"         "mgcv"         "rlang"        "scales"       "stats"       
[13] "tibble"       "vctrs"        "withr"        "utils"        "methods"      "nlme"        
[19] "graphics"     "Matrix"       "splines"      "farver"       "labeling"     "munsell"     
[25] "R6"           "RColorBrewer" "viridisLite"  "fansi"        "magrittr"     "pillar"      
[31] "pkgconfig"    "colorspace"   "lattice"      "utf8"  
```

**Comment by MichaelChirico** [comment]
ok so it's nice but not huge. could keep it or not I think either way is fine

**Comment by Anirban166** [comment]
Agreed. I think we should not install packages we do not require even if its for CI (so I'm gonna file a PR)

**Comment by tdhock** [comment]
in my opinion the 20 second speedup is not worth the added complexity

**Comment by tdhock** [comment]
rather than cherry picking deps to install, if we really want to make the installation faster, it should be profiled. what is the slowest step during the installation? I suspect it may be something other than installing deps, if we only gained 20 seconds here.

**Comment by MichaelChirico** [comment]
> in my opinion the 20 second speedup is not worth the added complexity

I think the complexity is only minimally higher, hence my indifference

> if we really want to make the installation faster

I was hoping to reduce the total execution time. that GHA starts to take a decent amount of time.

**Comment by Anirban166** [comment]
Actually, I'm getting mixed results on my fork - The difference might be much higher than 20 seconds (several minutes less) as I'm observing now..we'll have to get the new version running on `data.table` itself to see if that translates (I'll be sending a PR to change the `tests.R` file soon, so hopefully that shows some positive difference)

> > in my opinion the 20 second speedup is not worth the added complexity
> 
> I think the complexity is only minimally higher, hence my indifference
> 

Same thoughts, I don't think it's too bad in terms of complexity to use `install.packages(c("atime", "ggplot2", "directlabels"));` over `install.packages("atime", dependencies = TRUE);`

**Comment by Anirban166** [comment]
Actually, I'm getting mixed results on my fork - The difference might be much higher than 20 seconds (getting runs with several minutes less than former setup times) as I'm observing now..we'll have to get the new version running on `data.table` itself to see if that translates (I'll be sending a PR to change the `tests.R` file soon, so hopefully that shows some positive difference)

> > in my opinion the 20 second speedup is not worth the added complexity
> 
> I think the complexity is only minimally higher, hence my indifference
> 

Same thoughts, I don't think it's too bad in terms of complexity to use `install.packages(c("atime", "ggplot2", "directlabels"));` over `install.packages("atime", dependencies = TRUE);`
